### PR TITLE
Possible improvements

### PR DESCRIPTION
**Pull request by Dr-Emann**
I think the most interesting change is in 624457f

### CODE REVIEW

**Comment by yupferris** [comment]
Looks good to me :) mind fixing up the conflicts (as I pushed some changes yesterday), then I can do a proper review?

**Comment by Dr-Emann** [comment]
The first two commits are pretty innocuous. The last commit is more interesting..

**Comment by yupferris** [comment]
Yeah the first two look great! Thanks for that :)

As for the third, nice work! Cool idea to put the comm behind a read/write/seek interface, and the implementation looks sound and simple :) however I'm not sure I want to accept it for a couple reasons:
 - I'd like to keep message sending a bit more explicit. With this abstraction, the intent of communicating with the vb feels a bit obscured. On one hand that may be a benefit, since the top-level code may not care that it's talking to a vb. But on the other it's a bit odd to have to wrap the port in a separate object to perform the mem reads+writes when we have to use the fuzzy interface directly to execute code as well, so the API surface becomes a bit uneven, and loses a bit of the explicit-ness imo (plus I'd like the code to be explicit about the fact that it's communicating with a vb, and the io traits are not required for that).
 - I'm not a huge fan of using seek here actually, since it essentially turns one operation (read/write command) into two (seek + read/write command). While it certainly makes the fuzzy stuff more compatible with _other_ things that accept the std::io traits, I'd rather use code like this when we have an actual use case that demands such compatibility, and for the testing code I have in mind, it's not a requirement.

So I think overall it's best to leave that last commit out for now. But to reiterate, I do think it's kinda cool :) .

**Comment by Dr-Emann** [comment]
Yea, I kinda figured, I just saw the opportunity, and had to try it to see what it would be like. It _was_ nice that it handled the looping for larger reads automatically, though.

I've pulled that commit out, and merged master back in

**Comment by yupferris** [comment]
Thanks :)

**Pull request merged**
